---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
    exclude_fingerprints:
  eslint:
    enabled: true
    checks:
      linebreak-style:
        enabled: false
      guard-for-in:
        enabled: false
  fixme:
    enabled: true
ratings:
  paths:
  - "**.js"
  - "**.jsx"
exclude_paths:
- test/
